export default {
    BRAND_NAME: "Main Stack", // Change Brand name if new project
    LANDING: "Landing",

    AUTHENTICATION: "authentication",
    AUTHENTICATION_LANDING: "authenticationLanding",
    SIGNUP: "signup",
    SIGNUP_DETAILS: "signupDetails",
    SIGNUP_LICENSE: "signupLicense",
    SIGNUP_PASSWORD: "signupPassword",
    SIGNUP_PIN: "signupPin",
    LOGIN: "login",
    LOGIN_FORM: "loginForm",
    FORGOT_PASSWORD: "forgotPassword",
    PIN: "pin",
    ENTER_PIN: "enterPin",
    FORGOT_PIN: "forgotPin",
    AUTHENTICATED: "authenticated",
    MAIN_NAVIGATION: "mainNavigation",
    HOME: "home",
    NEW_LOG: "newLog",
    NEW_LOG_LANDING: "newLogLanding",
    CREATE_LOG_FOR_TODAY: "logForToday",
    HISTORY: "history",
    ACCOUNT: "account",
    CREATE_LOG: "createLogForToday",
    STARTING_DETAILS: "staringDetails",
    STARTING_VEHICLE: "startingVehicle",
    STARTING_COMPANY: "startingCompany",
    OVERVIEW: "overview",
    EVENT_DETAILS: "eventDetails",
    REVIEW_LIST: "reviewList",
    REVIEW_COMPANY_LIST: "reviewCompanyList",
    REVIEW_EDIT_COMPANY: "reviewEditCompany",
    HISTORY_LANDING: "historyLanding",
    HISTORY_TIMELINE_VIEW: "historyTimeline",
    HISTORY_LIST_VIEW: "historyListView",
    VIEW_EVENT: "viewEvent",
    EXPORT: "export",
    ACCOUNT_LANDING: "accountLanding",
    ACCOUNT_CHANGE_PASSWORD: "accountChangePassword",
    ACCOUNT_EDIT_LICENSE: "accountEditLicense",
    ACCOUNT_EDIT_COMPANY: "accountEditCompany"
  };
  